In [44]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [45]:
data=pd.read_csv(r'C:\Users\user\Desktop\smartbridge\Datasets\Social_Network_Ads.csv')

In [46]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [47]:
data.Purchased.value_counts()# Imbalanced data problem

0    257
1    143
Name: Purchased, dtype: int64

In [48]:
## Ddata Preprocessing
## EDA(uni,bi,multi)
## Data Handling()

In [49]:
data.drop('User ID',axis=1,inplace=True)

In [50]:
data.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

## Encoding

In [51]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [52]:
ca=LabelEncoder()

In [53]:
one=OneHotEncoder()

In [54]:
data.Gender=ca.fit_transform(data['Gender'])

In [55]:
data.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [56]:
x=data.drop('Purchased',axis=1)
y=data[['Purchased']]

In [57]:
x

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [58]:
y

Purchased
0            0
1            0
2            0
3            0
4            0
..         ...
395          1
396          1
397          1
398          0
399          1

[400 rows x 1 columns]

### Logistic Regression

In [59]:
from sklearn.model_selection import train_test_split

In [60]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.75,random_state=12)

## Handling Imbalanced data

In [61]:
pip install imblearn

Note: you may need to restart the kernel to use updated packages.


In [62]:
from imblearn.over_sampling import ADASYN,RandomOverSampler,BorderlineSMOTE,SMOTE

In [63]:
from imblearn.under_sampling import RandomUnderSampler

In [76]:
over=RandomUnderSampler()

In [77]:
x_train_balance,y_train_balanced=over.fit_resample(x_train,y_train)

In [78]:
y_train_balanced.value_counts()

Purchased
0            104
1            104
dtype: int64

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
lgr=LogisticRegression()

In [79]:
lgr.fit(x_train_balance,y_train_balanced)

LogisticRegression()

In [83]:
predict=lgr.predict(x_test)
predict

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [84]:
from sklearn.metrics import accuracy_score

In [85]:
accuracy_score(y_test,predict)

0.65

## Metrics

![metrics](https://i.ytimg.com/vi/9w4HJ0VUy2g/maxresdefault.jpg)

In [86]:
from sklearn.metrics import classification_report,confusion_matrix

In [87]:
print('report',classification_report(y_test,predict))

report               precision    recall  f1-score   support

           0       0.80      0.57      0.67        61
           1       0.54      0.77      0.63        39

    accuracy                           0.65       100
   macro avg       0.67      0.67      0.65       100
weighted avg       0.69      0.65      0.65       100



In [88]:
confusion_matrix(y_test,predict)

array([[35, 26],
       [ 9, 30]], dtype=int64)

## Support Vector Machine

It can be used for classification and regression, but most of the time we use for classification\
the best hyperplane\
Soft margin and Hard margin\
if our data is perfectly linearly seperable we will use hard margin\
if our data almost linearly seperable then we will use soft margin

### parameters
parameter:which is included in building the model\
hyperparameter: which will give you the best decision boundary,hyper plane,probability value

## Random Forest

In [89]:
from sklearn.ensemble import RandomForestClassifier

In [116]:
random=RandomForestClassifier(n_estimators= 171,bootstrap= True, max_depth= 6, max_features= 'auto', min_samples_leaf= 15, min_samples_split=12,)
random.fit(x_train_balance,y_train_balanced)

RandomForestClassifier(max_depth=6, min_samples_leaf=15, min_samples_split=12,
                       n_estimators=171)

In [117]:
predicct=random.predict(x_test)
predicct

array([1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1], dtype=int64)

In [118]:
accuracy_score(y_test,predicct)

0.86

In [119]:
confusion_matrix(y_test,predicct)

array([[50, 11],
       [ 3, 36]], dtype=int64)

### Hyper Tuning for Random Forest

## Random SearchCV

In [98]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

In [100]:
param_dist = {
    'n_estimators': randint(100, 1000),
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': randint(3, 10),
    'min_samples_split': randint(2, 20),
    'min_samples_leaf': randint(1, 20),
    'bootstrap': [True, False]
}

In [101]:
random_search = RandomizedSearchCV(
    estimator=random,
    param_distributions=param_dist,
    n_iter=10,
    cv=5,
    random_state=42
)

In [102]:
random_search.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002ACCD013940>,
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002ACCD013550>,
                                        'min_samples_split': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002ACCCF31490>,
                                        'n_estimators': <scipy.stats._distn_infrastructure.rv_discrete_frozen object at 0x000002ACCCE92FD0>},
                   random_state=42)

In [103]:
print(random_search.best_params_)

{'bootstrap': True, 'max_depth': 6, 'max_features': 'auto', 'min_samples_leaf': 15, 'min_samples_split': 12, 'n_estimators': 171}


In [106]:
random.estimator_params

('criterion',
 'max_depth',
 'min_samples_split',
 'min_samples_leaf',
 'min_weight_fraction_leaf',
 'max_features',
 'max_leaf_nodes',
 'min_impurity_decrease',
 'random_state',
 'ccp_alpha')

## GridSearchCV

In [121]:
from sklearn.model_selection import GridSearchCV

In [124]:
# Define the hyperparameter space
param_grid = {
    'n_estimators': [100, 500, 1000],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 5, 10],
    'bootstrap': [True, False]
}

In [125]:
grid_search = GridSearchCV(
    estimator=random,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1
)

In [126]:
# Fit the GridSearchCV object to the data
grid_search.fit(x_train_balance,y_train_balanced)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(max_depth=6, min_samples_leaf=15,
                                              min_samples_split=12,
                                              n_estimators=171),
             n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [3, 5, 7, 10],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 500, 1000]})

In [127]:
# Print the best hyperparameters
print(grid_search.best_params_)

{'bootstrap': False, 'max_depth': 5, 'max_features': 'auto', 'min_samples_leaf': 5, 'min_samples_split': 2, 'n_estimators': 500}


In [130]:
random=RandomForestClassifier(n_estimators=500,bootstrap= False, max_depth= 5, max_features= 'auto', min_samples_leaf= 5, min_samples_split=2,)
random.fit(x_train_balance,y_train_balanced)

RandomForestClassifier(bootstrap=False, max_depth=5, min_samples_leaf=5,
                       n_estimators=500)

In [131]:
pred=random.predict(x_test)

In [134]:
accuracy_score(y_test,pred)

0.86

In [133]:
confusion_matrix(y_test,pred)

array([[51, 10],
       [ 4, 35]], dtype=int64)

### Adaboost

In [47]:
from sklearn.ensemble import AdaBoostClassifier

In [48]:
ada=AdaBoostClassifier()

In [49]:
ada.fit(x_train,y_train)

AdaBoostClassifier()

In [50]:
boost=ada.predict(x_test)

In [51]:
accuracy_score(y_test,boost)

0.86

### XGBoost

In [53]:
pip install xgboost

     ---------------------------------------- 70.9/70.9 MB 5.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [54]:
from xgboost import XGBClassifier

In [55]:
xgb=XGBClassifier()

In [56]:
xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [57]:
pre=xgb.predict(x_test)
accuracy_score(y_test,pre)

0.84