### Numpy
Numpy is the core library for scientific computing in python. It provides a high- performance multidimentional array object, and tools for working with these arrays.

### Arrays
##### A numpy array is agrid of values, all of the same type, and is indexed by a tuple of non-negative integers.
The number of dimensions is the rank of the array;the shape of an array is a tuple of integers giving the size of the array along each dimension.

* numpy also has a powerful data type to define vectors(1-dimensional array), matrices(2-dimensional array)

* With these data types numpy also allows us to do linear algebra -
matrix multiplication and matrix-vector solutions

In [1]:
#Installation code
!pip install numpy

In [4]:
#Importing numpy library
import numpy as np

In [5]:
list_1 = [1,2,3,4,5]

In [11]:
arr= np.array(list_1)

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.min()

1

In [14]:
arr.max()

5

In [7]:
# Creating an array using list
list_1 = [1,2,3,4,5]
arr = np.array(list_1)
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
arr.shape   # shape is attribue

(5,)

In [9]:
arr.min()   # checking the minimum value of the array using min() function

1

In [10]:
arr.max()  # checking the maximun value of the array using max() function

5

In [20]:
arr.ndim

1

In [19]:
#accessing array
arr[0]

1

In [30]:
lst2=[[3,4,5,6],[1,2,3,4]]
lst2[1:3]

[[1, 2, 3, 4]]

In [25]:
twod=np.array(lst2)

In [26]:
twod

array([[3, 4, 5, 6],
       [1, 2, 3, 4]])

In [24]:
twod.ndim

2

In [ ]:
#two dimensional array
list_2 = [[1,2,3],[4,5,6]]
arr2d = np.array(list_2)

In [ ]:
type(arr2d)  # checking the type

numpy.ndarray

In [ ]:
arr2d.shape

(2, 3)

In [ ]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2d.ndim  # checking the dimension of the array

2

In [ ]:
arr.ndim

1

In [27]:
list_3 = [[1,2,3],[4,5,6],[7,8,9]]
arr_3 = np.array(list_3)

In [28]:
arr_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr_3.shape

(3, 3)

#### Indexing and Slicing

In [31]:
list_4 = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_4 = np.array(list_4)
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
arr_4[1:4] # slicing

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
arr_4[1,1]

6

In [46]:
arr_4[1,2]

7

In [7]:
arr_4[2,1]

10

In [14]:
arr_4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
arr_4[0:2,0:1]

array([[1],
       [5]])

In [49]:
arr_4[2:4,2:4]

array([[11, 12],
       [15, 16]])

In [ ]:
arr_4[0:3,1:4]

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [53]:
arr_4[0:2]=3
arr_4

array([[ 3,  3,  3,  3],
       [ 3,  3,  3,  3],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
# Broadcasting similar elements
arr_4[0:2] = 2
arr_4

array([[ 2,  2,  2,  2],
       [ 2,  2,  2,  2],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

### Functions used to creat Numpy arrays

In [58]:
# Zeros
zeros = np.zeros(6)
zeros

array([0., 0., 0., 0., 0., 0.])

In [60]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [61]:
# eye
eye = np.eye(5,5)  # Identity matrix
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [65]:
# arange
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(10,20,2) #starting,ending,stepsize

array([10, 12, 14, 16, 18])

In [68]:
np.linspace(5,10,100)

array([ 5.        ,  5.05050505,  5.1010101 ,  5.15151515,  5.2020202 ,
        5.25252525,  5.3030303 ,  5.35353535,  5.4040404 ,  5.45454545,
        5.50505051,  5.55555556,  5.60606061,  5.65656566,  5.70707071,
        5.75757576,  5.80808081,  5.85858586,  5.90909091,  5.95959596,
        6.01010101,  6.06060606,  6.11111111,  6.16161616,  6.21212121,
        6.26262626,  6.31313131,  6.36363636,  6.41414141,  6.46464646,
        6.51515152,  6.56565657,  6.61616162,  6.66666667,  6.71717172,
        6.76767677,  6.81818182,  6.86868687,  6.91919192,  6.96969697,
        7.02020202,  7.07070707,  7.12121212,  7.17171717,  7.22222222,
        7.27272727,  7.32323232,  7.37373737,  7.42424242,  7.47474747,
        7.52525253,  7.57575758,  7.62626263,  7.67676768,  7.72727273,
        7.77777778,  7.82828283,  7.87878788,  7.92929293,  7.97979798,
        8.03030303,  8.08080808,  8.13131313,  8.18181818,  8.23232323,
        8.28282828,  8.33333333,  8.38383838,  8.43434343,  8.48

In [ ]:
# linspace
linspace = np.linspace(0,10,20)  #linearly space elements , 
            #20 is the number how many u want to linearly space the values
linspace

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [72]:
# random.rand
np.random.rand(5)# (0,1 -->numbers will be within 0 & 1)

array([0.92984003, 0.27984405, 0.32383358, 0.44849345, 0.57203944])

In [74]:
np.random.rand(4,4) # 3 rows and 5 columns

array([[0.81539311, 0.13415465, 0.01726861, 0.54321623],
       [0.93252332, 0.2113118 , 0.75753834, 0.56451397],
       [0.11552746, 0.25556354, 0.11012877, 0.54836121],
       [0.41226216, 0.66957174, 0.49718549, 0.50345197]])

In [77]:
# randint
np.random.randint(1,100)

79

In [78]:
np.random.randint(1,100)

95

In [79]:
np.random.randint(1,100,5) # 5 specifies number of elements u want to fetch

array([70, 52, 37, 23, 61])

In [30]:
arr = np.arange(1,17)
arr.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [87]:
a=np.arange(1,10)
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
# reshape -- Convert 1d  to 2d
arr = np.arange(1,17)
arr2 = arr.reshape(4,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [93]:
array1 = np.arange(1,10)
array2 = array1.reshape(3,3)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
w=np.linspace(0,7,9).reshape(3,3)

In [91]:

ar1 = np.linspace(0,7,9).reshape(3,3)
ar1

array([[0.   , 0.875, 1.75 ],
       [2.625, 3.5  , 4.375],
       [5.25 , 6.125, 7.   ]])

In [38]:
a = "Hello"
b = "World"
a+b

'HelloWorld'

In [94]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
ar1

array([[0.   , 0.875, 1.75 ],
       [2.625, 3.5  , 4.375],
       [5.25 , 6.125, 7.   ]])

In [98]:
np.concatenate((ar1,array2),axis=1)

array([[0.   , 0.875, 1.75 , 1.   , 2.   , 3.   ],
       [2.625, 3.5  , 4.375, 4.   , 5.   , 6.   ],
       [5.25 , 6.125, 7.   , 7.   , 8.   , 9.   ]])

In [99]:
conc = np.concatenate((array2,ar1),axis = 0)  # 0-->rows
conc

array([[1.   , 2.   , 3.   ],
       [4.   , 5.   , 6.   ],
       [7.   , 8.   , 9.   ],
       [0.   , 0.875, 1.75 ],
       [2.625, 3.5  , 4.375],
       [5.25 , 6.125, 7.   ]])

In [100]:
conc = np.concatenate((array2,ar1),axis = 1)  # 1-->columns
conc

array([[1.   , 2.   , 3.   , 0.   , 0.875, 1.75 ],
       [4.   , 5.   , 6.   , 2.625, 3.5  , 4.375],
       [7.   , 8.   , 9.   , 5.25 , 6.125, 7.   ]])

In [103]:
#delete
np.delete(conc,1,axis = 1)

array([[1.   , 3.   , 0.   , 0.875, 1.75 ],
       [4.   , 6.   , 2.625, 3.5  , 4.375],
       [7.   , 9.   , 5.25 , 6.125, 7.   ]])

In [104]:
np.delete(conc,2,axis=0)

array([[1.   , 2.   , 3.   , 0.   , 0.875, 1.75 ],
       [4.   , 5.   , 6.   , 2.625, 3.5  , 4.375]])

In [105]:
#ravel
ar2 = np.arange(10)
ar2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
ar2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
ravel = ar2.ravel()
flatten = ar2.flatten()
print(ravel)  # ravel is faster than flatten and it does not occupy memory
print(flatten) # ravel just takes the reference of the original array

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [108]:
ravel[5] = 20
ravel

array([ 0,  1,  2,  3,  4, 20,  6,  7,  8,  9])

In [109]:
ar2  # the original array is also changed

array([ 0,  1,  2,  3,  4, 20,  6,  7,  8,  9])

In [72]:
# flatten returns the original copy of the array and flatten occupies memory
flatten[0] = 100
flatten

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [73]:
ar2 # the original array did not change

array([ 0,  1,  2,  3,  4, 20,  6,  7,  8,  9])

### Numpy Operations

In [110]:
import warnings
warnings.filterwarnings("ignore")

In [111]:
ar3 = np.arange(0,10)
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
ar3 + ar3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
ar3 * ar3 #mutliplication

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
ar3 - ar3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ar3/ar3

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
np.sqrt(ar3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.log(ar3)

array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
np.min(ar3)

0

In [ ]:
np.max(ar3)

9

In [114]:
ar3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
np.argmax(ar3) # return index position of the highest number

9

In [113]:
np.argmin(ar3) # return index position of the lowest number

0